### ISSUE TITLE
Open discussion about site improvements

### ISSUE THREAD

**Issue by nicinabox** [stylelint/stylelint.github.io#2]
I tweeted this earlier, just wanted to follow up on it:
https://twitter.com/nicinabox/status/674970069215125504

The biggest issue with the site right now is how docs are loaded (ajax). This creates some awkward usability issues (not possible to open tabs, compare multiple docs, losing scroll position on back, etc).

I'm not sure what the next best step is, but I'm happy to help improve this. Maybe @davidtheclark has a vision for this?

**Comment by jeddy3** [comment]
> This creates some awkward usability issues (not possible to open tabs, compare multiple docs, losing scroll position on back, etc).

No kidding. I almost cried myself to sleep after I hurriedly put-together the JavaScript for the website :)

> I'm not sure what the next best step is

Maxime, one of stylelint's original authors, was working on a react-based static site generator (https://github.com/MoOx/statinamic), which we had kind-of ear-marked to help us out. However, I've not had time to look into it.

> but I'm happy to help improve this 

I'm not sure what David's thoughts are on this, but if you're willing to help out then I'm happy for you suggest whatever solution is easiest for you. One thing though, if we do go down something like a react route then I'd be nice to see something like CSS Modules in use, rather than inline styles... so we can lint the CSS with stylelint i.e. provide a real-world example of it's use and dog food our own work.

**Comment by jeddy3** [comment]
Or... we could use a tool like GitBooks to create something along the lines of http://airbnb.io/enzyme/

Open to ideas.

**Comment by nicinabox** [comment]
> No kidding. I almost cried myself to sleep after I hurriedly put-together the JavaScript for the website :)

Ha! This is exactly the impression I got. Da real MVP. 

> so we can lint the CSS with stylelint i.e. provide a real-world example of it's use and dog food our own work.

:100: :100: :100: 

Just spitballing here:

My initial thought is that using Github Pages/Jekyll could be fine. It's simple and well documented, yet still flexible enough to meet dogfooding criteria. (Aside: I just realized this is a github.io repo, not a gh-pages branch).

There's some question of where the source docs should live (I know I've seen other projects do this, but can't think of one off the top of my head right now). I feel like keeping them with the main repo is ideal, but I'm not sure.

It would nice from a matter of process if deploying docs changes was dead easy. I'm not opposed to using React to build it, but the source complexity might not be warranted for such a simple site. Open to ideas about this.

Depending on how the site is hosted might influence how it's architected too. `gh-pages` wants to be Jekyll. Github User Pages typically wants `index.html` in the root. I've been getting really into [surge.sh](http://surge.sh/) lately. I usually deploy a dist/ directory with the build. Might be an option?

What would be the absolute simplest thing to do regular server side rendering? Where do we want to go from there? What kinds of interactivity might we want to support later on? (eg, interactive linter?)

**Comment by jeddy3** [comment]
> There's some question of where the source docs should live

Each rule is very much standalone. The source source code, tests and documentation are all contained within the same folder. It'd be great to keep this system in place, which means the documentation would, ideally, remain within the `stylelint/stylelint` repo. 

> Where do we want to go from there? What kinds of interactivity might we want to support later on? (eg, interactive linter?)

An interactive linter would be fab. I can't imagine us ever wanting more than that.

So, I guess something similar to http://eslint.org/ would be ideal:

1. A set of static pages built from the `.md` files within the main repo.
2. An interactive linter.

The interactive linter will likely involve the most client-side code, so perhaps we work out what we need to put in place to make that happen, and then see if any of that stuff is useful in solving the first requirement too. What do you think?

**Comment by jeddy3** [comment]
Dumping some examples of interactive playgrounds:

ESLint: https://github.com/eslint/eslint/blob/master/Makefile.js#L651 / http://eslint.org/js/app/demo.js
CSSNext: https://github.com/cssnext/cssnext/tree/master/docs/src/modules/playground
Pleeaase: https://github.com/iamvdo/pleeease-website/tree/gh-pages/app/playground
Component playground: http://projects.formidablelabs.com/component-playground/

Got more?

**Comment by nicinabox** [comment]
Given the similarities between the ESLint syntax and stylelint syntax, a playground similar to ESLint's could be really nice.

I'm also noticing they have docs in both repos, but they are not identical.

https://github.com/eslint/eslint.github.io/tree/master/docs
https://github.com/eslint/eslint/tree/master/docs/rules

**Comment by nicinabox** [comment]
These actually look copied from the main repo. Maybe there's a whirlygig.
https://github.com/eslint/eslint.github.io/tree/f2831f59edfa0284f0f13f7291ad74fe921c2b61/docs/1.0.0/rules

**Comment by davidtheclark** [comment]
Another nice thing for this kind of project (with lots of docs): a search that's autofocused so you can quickly type a rule name and get the rule's docs.

**Comment by nicinabox** [comment]
Seems like a bunch of folks are using Algolia these days (eslint, react.parts, others?).

**Comment by davidtheclark** [comment]
Here are my more extended thoughts:

- I like the way that we have our documentation setup (READMEs within rule directories), so I would like the static site generator to find those files and use them, rather than us having to move those files. My vision, really, is that the website simply publishes the markdown files in a nice presentation with clean, organized URLs.
- I think that if we set our site up nicely with one static site generator (e.g. Jekyll) and later Maxime has his React-powered generator going, we can easily switch. The real bulk of the work should be in the individual markdown files. So I'd be happy to go with whatever generator is preferable to whoever builds the site.
- I think static HTML with clean URLs would be best, no JS necessary. That way we simply don't have to worry about any of the problems caused by *not* having static HTML. There's no interactivity here: just URLs with documents.
- The sooner this can happen the better. @nicinabox if you feel like taking the lead on this that would be awesome. Please let us know if you don't have the time, though, so we don't twiddle our thumbs and realize we shouldn't have been waiting. What do you think?

**Comment by nicinabox** [comment]
> I would like the static site generator to find those files and use them, rather than us having to move those files.

Absolutely. We should be able to automate this. 

> There's no interactivity here: just URLs with documents.

Exactly what I had in mind.

> Please let us know if you don't have the time, though, so we don't twiddle our thumbs and realize we shouldn't have been waiting.

I'd be happy to take the lead on this. We are coming into heavy holiday season though. Still, this is a fairly straightforward project. I don't expect it will drag on for months. It would be good to have it wrapped up by the end of January, but I hope it would be quicker than that.

**Comment by nicinabox** [comment]
See #3 for a summary of this discussion and proposed changes.

**Comment by MoOx** [comment]
FYI, [statinamic](http://moox.io/statinamic/) is young but works (eg: http://putaindecode.io/). I can provide help to setup (also: https://github.com/putaindecode/putaindecode.io)

**Comment by DanGamble89** [comment]
Just to pipe up i wouldn't mind pitching into this once it's underway :)

**Comment by MoOx** [comment]
FYI, PostCSS incoming website will be based on Statinamic.
